# Generated by Django 3.1.7 on 2021-03-04 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New order'), ('in_process', 'Order is in process'), ('renouncement', 'Order is declined'), ('complete', 'Order is complete')], default='new', max_length=30)),
                ('delivery', models.BooleanField(default=False, null=True)),
                ('delivery_address', models.CharField(max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=40, null=True)),
                ('total_cost', models.FloatField(blank=True, null=True)),
                ('cart', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
            ],
        ),
    ]
