# Generated by Django 3.1.7 on 2021-03-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210305_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created',
            field=models.BooleanField(default=False, verbose_name='created'),
        ),
    ]
