# Generated by Django 3.1.7 on 2021-03-05 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210305_2234'),
        ('cart', '0003_auto_20210305_1938'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
