# Generated by Django 3.1.7 on 2021-03-05 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manufacturer',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='product',
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
    ]
